source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'


require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

# 默认false,设置为true则如果是多工程的则会有多个Pods.xcodeproj
install! 'cocoapods', :generate_multiple_pod_projects => false
install! 'cocoapods', :deterministic_uuids => false

target 'overts' do
  
  config = use_native_modules!
  
  #pod 'Flipper', :git => 'https://e.coding.net/zhuzijia/import/flipper.git'
  
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  
  target 'overtsTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  #use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
